import {Router} from 'express';import {z} from 'zod';import {db} from '../index.js';import {auth,requireRole,type AuthedRequest} from '../middleware/auth.js'; import {requireApprovedOfflineDevice} from '../middleware/offlineDevice.js';
export const assetsRouter=Router();assetsRouter.use(auth); assetsRouter.use(requireApprovedOfflineDevice);
const serialize=(x:any):any=>typeof x==='bigint'?x.toString():Array.isArray(x)?x.map(serialize):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,serialize(v)])):x;
const input=z.object({assetCategoryId:z.coerce.number().int().positive(),name:z.string().min(1),quantity:z.coerce.number().int().min(0),valueRwf:z.coerce.bigint().nonnegative().nullable().optional(),location:z.string().optional().default(''),custodian:z.string().optional().default(''),condition:z.string().optional().default(''),notes:z.string().optional().default(''),submissionId:z.string().min(8)});
function scope(u:any){return u.role==='REGIONAL_LEADER'?{}:{churchId:u.churchId??-1};}
assetsRouter.get('/categories',async(req:AuthedRequest,res)=>{
  const all=req.query.all==='1'&&req.user?.role==='REGIONAL_LEADER';
  res.json(await db.assetCategory.findMany({where:all?{}:{isActive:true},orderBy:{name:'asc'}}));
});
assetsRouter.post('/categories',requireRole('REGIONAL_LEADER'),async(req,res)=>{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({message:'Name is required'});try{res.status(201).json(await db.assetCategory.create({data:{name}}))}catch{res.status(409).json({message:'That category already exists'})}});
assetsRouter.patch('/categories/:id',requireRole('REGIONAL_LEADER'),async(req,res)=>{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({message:'Name is required'});try{res.json(await db.assetCategory.update({where:{id:Number(req.params.id)},data:{name}}))}catch{res.status(409).json({message:'That category already exists'})}});
assetsRouter.post('/categories/:id/active',requireRole('REGIONAL_LEADER'),async(req,res)=>res.json(await db.assetCategory.update({where:{id:Number(req.params.id)},data:{isActive:req.body.isActive!==false}})));
assetsRouter.get('/',async(req:AuthedRequest,res)=>res.json(serialize(await db.asset.findMany({where:{...scope(req.user!),isActive:true},orderBy:{name:'asc'}}))));
assetsRouter.post('/',requireRole('CHURCH'),async(req:AuthedRequest,res)=>{const p=input.safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid asset',issues:p.error.issues});res.status(201).json(serialize(await db.asset.create({data:{...p.data,churchId:req.user!.churchId!}})))});
assetsRouter.patch('/:id',requireRole('CHURCH'),async(req:AuthedRequest,res)=>{const id=Number(req.params.id),u=req.user!;const old=await db.asset.findFirst({where:{id,churchId:u.churchId!,isActive:true}});if(!old)return res.status(404).json({message:'Asset not found or not editable'});const p=input.omit({submissionId:true}).partial().safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid asset'});res.json(serialize(await db.asset.update({where:{id},data:{...p.data,revision:{increment:1}}})))});
assetsRouter.post('/:id/archive',requireRole('CHURCH'),async(req:AuthedRequest,res)=>{const id=Number(req.params.id),u=req.user!;const old=await db.asset.findFirst({where:{id,churchId:u.churchId!,isActive:true}});if(!old)return res.status(404).json({message:'Asset not found or not editable'});res.json(serialize(await db.asset.update({where:{id},data:{isActive:false,revision:{increment:1}}})))});
