import {Router} from 'express'; import {db} from '../index.js'; import {auth,requireRole,type AuthedRequest} from '../middleware/auth.js'; import {requireApprovedOfflineDevice} from '../middleware/offlineDevice.js'; export const membersRouter=Router(); membersRouter.use(auth); membersRouter.use(requireApprovedOfflineDevice);
function scope(u:any){if(u.role==='REGIONAL_LEADER')return {};if(u.role==='CHURCH')return {group:{section:{churchId:u.churchId}}};if(u.role==='SECTION')return {group:{sectionId:u.sectionId}};return {groupId:u.groupId}}
membersRouter.get('/',async(req:AuthedRequest,res)=>res.json(await db.member.findMany({where:scope(req.user),include:{group:{include:{section:true}}},orderBy:{fullName:'asc'}})));
membersRouter.post('/',requireRole('CHURCH','SECTION','GROUP'),async(req:AuthedRequest,res)=>{const u=req.user!;const groupId=u.role==='GROUP'?u.groupId!:Number(req.body.groupId);const g=await db.group.findUnique({where:{id:groupId},include:{section:true}});if(!g||!g.isActive||!g.section.isActive)return res.status(400).json({message:'Invalid or inactive group'});if(u.role==='CHURCH'&&g.section.churchId!==u.churchId||u.role==='SECTION'&&g.sectionId!==u.sectionId)return res.status(403).json({message:'Outside your scope'});const fullName=String(req.body.fullName||'').trim();if(!fullName)return res.status(400).json({message:'Full name is required'});const phone=String(req.body.phoneNumber||'').trim()||null;const submissionId=String(req.body.submissionId||'').trim();if(submissionId.length<8)return res.status(400).json({message:'submissionId is required'});const duplicate=await db.member.findUnique({where:{submissionId}});if(duplicate)return res.json(duplicate);try{res.status(201).json(await db.member.create({data:{fullName,phoneNumber:phone,groupId,submissionId}}))}catch{return res.status(409).json({message:'Phone number already exists or data is invalid'})}});
async function editableMember(u:any,id:number){const m=await db.member.findFirst({where:{id,...scope(u)},include:{group:{include:{section:true}}}});if(!m)return null;if(u.role==='REGIONAL_LEADER')return null;return m}
membersRouter.patch('/:id',requireRole('CHURCH','SECTION','GROUP'),async(req:AuthedRequest,res)=>{
 const u=req.user!; const current=await editableMember(u,Number(req.params.id)); if(!current)return res.status(404).json({message:'Member not found in your scope'});
 const fullName=String(req.body.fullName||'').trim(); if(!fullName)return res.status(400).json({message:'Full name is required'});
 const phone=String(req.body.phoneNumber??'').trim()||null;
 let groupId=current.groupId;
 if(u.role!=='GROUP'&&req.body.groupId){groupId=Number(req.body.groupId); const g=await db.group.findUnique({where:{id:groupId},include:{section:true}}); if(!g||!g.isActive)return res.status(400).json({message:'Invalid or inactive group'}); if(u.role==='CHURCH'&&g.section.churchId!==u.churchId||u.role==='SECTION'&&g.sectionId!==u.sectionId)return res.status(403).json({message:'Outside your scope'});}
 try{res.json(await db.member.update({where:{id:current.id},data:{fullName,phoneNumber:phone,groupId,isActive:req.body.isActive!==false}}))}catch{res.status(409).json({message:'Phone number already exists or data is invalid'})}
});
membersRouter.post('/:id/active',requireRole('CHURCH','SECTION','GROUP'),async(req:AuthedRequest,res)=>{
 const current=await editableMember(req.user,Number(req.params.id)); if(!current)return res.status(404).json({message:'Member not found in your scope'});
 res.json(await db.member.update({where:{id:current.id},data:{isActive:req.body.isActive!==false}}));
});
