import {Router} from 'express';
import {db} from '../index.js';
import {auth,type AuthedRequest} from '../middleware/auth.js';
export const reportsRouter=Router(); reportsRouter.use(auth);
const serialize=(x:any):any=>typeof x==='bigint'?x.toString():Array.isArray(x)?x.map(serialize):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,serialize(v)])):x;
function contributionScope(u:any){const w:any={isCancelled:false};if(u.role==='CHURCH')w.churchId=u.churchId;if(u.role==='SECTION')w.sectionIdAtEntry=u.sectionId;if(u.role==='GROUP')w.groupIdAtEntry=u.groupId;return w}
function memberScope(u:any){if(u.role==='REGIONAL_LEADER')return {};if(u.role==='CHURCH')return {group:{section:{churchId:u.churchId}}};if(u.role==='SECTION')return {group:{sectionId:u.sectionId}};return {groupId:u.groupId}}
reportsRouter.get('/summary',async(req:AuthedRequest,res)=>{const u=req.user!;const start=req.query.start?new Date(String(req.query.start)):undefined;const end=req.query.end?new Date(String(req.query.end)+'T23:59:59.999'):undefined;const contributionTypeId=req.query.contributionTypeId?Number(req.query.contributionTypeId):undefined;const where:any={...contributionScope(u)};if(contributionTypeId)where.contributionTypeId=contributionTypeId;if(start||end)where.receivedAt={...(start?{gte:start}:{}),...(end?{lte:end}:{})};const agg=await db.contribution.aggregate({_sum:{amountRwf:true},_count:{_all:true},where});const memberCount=await db.member.count({where:{...memberScope(u),isActive:true}});res.json(serialize({memberCount,contributionEntries:agg._count._all,totalContributed:agg._sum.amountRwf??0n,individualAmountsVisible:u.role==='REGIONAL_LEADER'}))});
reportsRouter.get('/believers',async(req:AuthedRequest,res)=>{const u=req.user!;const start=req.query.start?new Date(String(req.query.start)):undefined;const end=req.query.end?new Date(String(req.query.end)+'T23:59:59.999'):undefined;const contributionTypeId=req.query.contributionTypeId?Number(req.query.contributionTypeId):undefined;const members=await db.member.findMany({where:{...memberScope(u),isActive:true},include:{group:{include:{section:{include:{church:true}}}}},orderBy:{fullName:'asc'}});const rows=[];for(const m of members){const w:any={memberId:m.id,isCancelled:false};if(contributionTypeId)w.contributionTypeId=contributionTypeId;if(start||end)w.receivedAt={...(start?{gte:start}:{}),...(end?{lte:end}:{})};const a=await db.contribution.aggregate({_sum:{amountRwf:true},_count:{_all:true},where:w});rows.push({memberId:m.id,fullName:m.fullName,church:m.group.section.church.name,section:m.group.section.name,group:m.group.name,status:a._count._all>0?'Yego':'Oya',amountRwf:u.role==='REGIONAL_LEADER'?(a._sum.amountRwf??0n):undefined})}res.json(serialize({amountsVisible:u.role==='REGIONAL_LEADER',rows}))});
reportsRouter.get('/budget-performance',async(req:AuthedRequest,res)=>{const u=req.user!;const budgetId=Number(req.query.budgetId);if(!budgetId)return res.status(400).json({message:'budgetId required'});const b=await db.budget.findUnique({where:{id:budgetId},include:{metrics:true}});if(!b)return res.status(404).json({message:'Budget not found'});const rows=[];for(const m of b.metrics){let target=0n;if(u.role==='CHURCH')target=(await db.budgetChurchAllocation.findUnique({where:{budgetMetricId_churchId:{budgetMetricId:m.id,churchId:u.churchId!}}}))?.targetValue??0n;else if(u.role==='SECTION')target=(await db.budgetSectionAllocation.findUnique({where:{budgetMetricId_sectionId:{budgetMetricId:m.id,sectionId:u.sectionId!}}}))?.targetValue??0n;else if(u.role==='GROUP')target=(await db.budgetGroupAllocation.findUnique({where:{budgetMetricId_groupId:{budgetMetricId:m.id,groupId:u.groupId!}}}))?.targetValue??0n;else target=(await db.budgetChurchAllocation.aggregate({_sum:{targetValue:true},where:{budgetMetricId:m.id}}))._sum.targetValue??0n;let achievement=0n;if(m.contributionTypeId){const w:any={...contributionScope(u),contributionTypeId:m.contributionTypeId,receivedAt:{gte:b.startDate,lte:b.endDate}};achievement=(await db.contribution.aggregate({_sum:{amountRwf:true},where:w}))._sum.amountRwf??0n}else{const w:any={budgetMetricId:m.id};if(u.role==='CHURCH')w.churchId=u.churchId;if(u.role==='SECTION')w.sectionId=u.sectionId;if(u.role==='GROUP')w.groupId=u.groupId;achievement=(await db.budgetAchievement.aggregate({_sum:{quantity:true},where:w}))._sum.quantity??0n}rows.push({metricId:m.id,name:m.name,target,achievement,percentage:target===0n?0:Number(achievement*10000n/target)/100,remaining:target>achievement?target-achievement:0n})}res.json(serialize({budget:{id:b.id,name:b.name,startDate:b.startDate,endDate:b.endDate,status:b.status},rows}))});
