import {Router} from 'express';
import {db} from '../index.js';
import {auth,AuthedRequest} from '../middleware/auth.js'; import {requireApprovedOfflineDevice} from '../middleware/offlineDevice.js';

export const sabbathSchoolRouter=Router();
sabbathSchoolRouter.use(auth); sabbathSchoolRouter.use(requireApprovedOfflineDevice);

function scopeWhere(u:NonNullable<AuthedRequest['user']>){
  if(u.role==='REGIONAL_LEADER') return {};
  if(u.role==='CHURCH') return {churchId:u.churchId!};
  if(u.role==='SECTION') return {sectionId:u.sectionId!};
  if(u.role==='GROUP') return {groupId:u.groupId!};
  return {id:-1};
}
function canWriteGroup(u:NonNullable<AuthedRequest['user']>,groupId:number){
  return u.role==='GROUP' && u.groupId===groupId;
}
function parseDay(value:unknown){
  const text=String(value||'').trim().slice(0,10);
  if(!/^\d{4}-\d{2}-\d{2}$/.test(text)) return null;
  const [year,month,day]=text.split('-').map(Number);
  const date=new Date(Date.UTC(year,month-1,day));
  if(date.getUTCFullYear()!==year||date.getUTCMonth()!==month-1||date.getUTCDate()!==day) return null;
  return date;
}
function dayText(date:Date){return date.toISOString().slice(0,10);}

// Entries are created at Itsinda level only. Date is generated by the server.
sabbathSchoolRouter.post('/',async(req:AuthedRequest,res)=>{
  const groupId=Number(req.body.groupId??req.user!.groupId);
  if(!Number.isInteger(groupId)||!canWriteGroup(req.user!,groupId)) return res.status(403).json({message:'Ishuri ryo ku Isabato ryinjizwa n\'Itsinda ryemerewe gusa.'});
  const submissionId=String(req.body.submissionId||'').trim();
  if(submissionId.length<8) return res.status(400).json({message:'submissionId is required'});
  const duplicate=await db.sabbathSchoolEntry.findUnique({where:{submissionId}});
  if(duplicate) return res.json(duplicate);
  const payload=req.body.payload;
  if(!payload||typeof payload!=='object'||Array.isArray(payload)) return res.status(400).json({message:'Statistics payload is required.'});
  const group=await db.group.findUnique({where:{id:groupId},include:{section:true}});
  if(!group||!group.isActive) return res.status(404).json({message:'Itsinda ntiryabonetse.'});
  const row=await db.sabbathSchoolEntry.create({data:{groupId,sectionId:group.sectionId,churchId:group.section.churchId,createdByUserId:req.user!.id,payloadJson:payload,submissionId}});
  res.status(201).json(row);
});

sabbathSchoolRouter.get('/',async(req:AuthedRequest,res)=>{
  const rows=await db.sabbathSchoolEntry.findMany({where:scopeWhere(req.user!),orderBy:{entryDateUtc:'desc'},take:500});
  res.json(rows);
});

// Generic numeric roll-up keeps approved statistics intact without hard-coding new fields.
sabbathSchoolRouter.get('/summary',async(req:AuthedRequest,res)=>{
  const from=req.query.from?new Date(String(req.query.from)):undefined;
  const to=req.query.to?new Date(String(req.query.to)):undefined;
  const where:any={...scopeWhere(req.user!)};
  if(from||to) where.entryDateUtc={...(from?{gte:from}:{}),...(to?{lte:to}:{})};
  const rows=await db.sabbathSchoolEntry.findMany({where,orderBy:{entryDateUtc:'asc'}});
  const totals:Record<string,number>={};
  for(const row of rows){
    const p=row.payloadJson as Record<string,unknown>;
    for(const [k,v] of Object.entries(p)) if(typeof v==='number'&&Number.isFinite(v)) totals[k]=(totals[k]||0)+v;
  }
  res.json({scope:req.user!.role,entryCount:rows.length,totals,from:from?.toISOString()??null,to:to?.toISOString()??null});
});

sabbathSchoolRouter.get('/attendance',async(req:AuthedRequest,res)=>{
  const u=req.user!;
  if(u.role!=='GROUP'||!u.groupId) return res.status(403).json({message:'Itsinda ni ryo ryonyine ryandika kwitabira.'});
  const entryDate=parseDay(req.query.date);
  if(!entryDate) return res.status(400).json({message:'Itariki irakenewe.'});
  const members=await db.member.findMany({where:{groupId:u.groupId,isActive:true},orderBy:{fullName:'asc'}});
  const marks=await db.sabbathAttendance.findMany({where:{groupId:u.groupId,entryDate}});
  const byMember=new Map(marks.map(mark=>[mark.memberId,mark]));
  res.json({
    date:dayText(entryDate),
    saved:marks.length>0,
    members:members.map(member=>{
      const mark=byMember.get(member.id);
      return {id:member.id,fullName:member.fullName,present:mark?mark.present:null,absenceReason:mark?.absenceReason??null,absenceNote:mark?.absenceNote??null};
    })
  });
});

sabbathSchoolRouter.put('/attendance',async(req:AuthedRequest,res)=>{
  const u=req.user!;
  if(u.role!=='GROUP'||!u.groupId) return res.status(403).json({message:'Itsinda ni ryo ryonyine ryandika kwitabira.'});
  const entryDate=parseDay(req.body.date);
  if(!entryDate) return res.status(400).json({message:'Itariki irakenewe.'});
  if(!Array.isArray(req.body.marks)) return res.status(400).json({message:'Erekana kwitabira kw’abizera bose.'});
  const members=await db.member.findMany({where:{groupId:u.groupId,isActive:true}});
  if(!members.length) return res.status(400).json({message:'Nta mwizera ukora muri iki tsinda.'});
  const allowed=new Set(members.map(member=>member.id));
  const seen=new Set<number>();
  const reasons=new Set(['sick','other_church','other']);
  const rows:{memberId:number;present:boolean;absenceReason:string|null;absenceNote:string|null}[]=[];
  for(const mark of req.body.marks){
    const memberId=Number(mark?.memberId);
    if(!allowed.has(memberId)||seen.has(memberId)||typeof mark?.present!=='boolean') return res.status(400).json({message:'Erekana kwitabira kw’abizera bose.'});
    let absenceReason:string|null=null;
    let absenceNote:string|null=null;
    if(!mark.present){
      absenceReason=String(mark.absenceReason||'');
      if(!reasons.has(absenceReason)) return res.status(400).json({message:'Hitamo impamvu yo kutaza.'});
      absenceNote=String(mark.absenceNote||'').trim()||null;
      if(absenceReason==='other'&&!absenceNote) return res.status(400).json({message:'Andika impamvu.'});
      if(absenceNote&&absenceNote.length>160) return res.status(400).json({message:'Impamvu ni ndende cyane.'});
      if(absenceReason!=='other') absenceNote=null;
    }
    seen.add(memberId);
    rows.push({memberId,present:mark.present,absenceReason,absenceNote});
  }
  if(seen.size!==allowed.size) return res.status(400).json({message:'Erekana kwitabira kw’abizera bose.'});
  const group=await db.group.findUnique({where:{id:u.groupId},include:{section:true}});
  if(!group||!group.isActive) return res.status(404).json({message:'Itsinda ntiryabonetse.'});
  try{
    await db.$transaction(async tx=>{
      await tx.sabbathAttendance.deleteMany({where:{groupId:u.groupId!,entryDate}});
      await tx.sabbathAttendance.createMany({data:rows.map(row=>({churchId:group.section.churchId,sectionId:group.sectionId,groupId:u.groupId!,memberId:row.memberId,entryDate,present:row.present,absenceReason:row.absenceReason,absenceNote:row.absenceNote,createdByUserId:u.id}))});
    });
  }catch{return res.status(409).json({message:'Kwitabira ntikwabitswe. Umwizera ashobora kuba yaranditswe ku yindi tariki.'});}
  res.json({date:dayText(entryDate),saved:rows.length});
});

sabbathSchoolRouter.get('/attendance/report',async(req:AuthedRequest,res)=>{
  const to=parseDay(req.query.to);
  const from=parseDay(req.query.from);
  if(!from||!to) return res.status(400).json({message:'Itariki irakenewe.'});
  if(from>to) return res.status(400).json({message:'Itariki irangira ntishobora kubanziriza itangira.'});
  const marks=await db.sabbathAttendance.findMany({
    where:{...scopeWhere(req.user!),entryDate:{gte:from,lte:to}},
    include:{member:{select:{fullName:true}},group:{select:{id:true,name:true,section:{select:{name:true,church:{select:{name:true}}}}}}},
    orderBy:[{entryDate:'desc'},{groupId:'asc'},{memberId:'asc'}]
  });
  const grouped=new Map<string,{date:string;church:string;section:string;group:string;present:number;absent:number}>();
  for(const mark of marks){
    const date=dayText(mark.entryDate);
    const key=`${date}:${mark.groupId}`;
    const row=grouped.get(key)||{date,church:mark.group.section.church.name,section:mark.group.section.name,group:mark.group.name,present:0,absent:0};
    if(mark.present) row.present+=1; else row.absent+=1;
    grouped.set(key,row);
  }
  res.json({
    from:dayText(from),
    to:dayText(to),
    present:marks.filter(mark=>mark.present).length,
    absent:marks.filter(mark=>!mark.present).length,
    groups:[...grouped.values()],
    rows:marks.map(mark=>({id:mark.id,date:dayText(mark.entryDate),church:mark.group.section.church.name,section:mark.group.section.name,group:mark.group.name,fullName:mark.member.fullName,present:mark.present,absenceReason:mark.absenceReason,absenceNote:mark.absenceNote}))
  });
});

sabbathSchoolRouter.patch('/:id',async(req:AuthedRequest,res)=>{
  const id=Number(req.params.id);
  const row=await db.sabbathSchoolEntry.findFirst({where:{id,...scopeWhere(req.user!)}});
  if(!row||!canWriteGroup(req.user!,row.groupId)) return res.status(403).json({message:'Only the owning Itsinda can change this entry.'});
  const payload=req.body.payload;
  if(!payload||typeof payload!=='object'||Array.isArray(payload)||!Object.keys(payload).length) return res.status(400).json({message:'Statistics payload is required.'});
  res.json(await db.sabbathSchoolEntry.update({where:{id},data:{payloadJson:payload,revision:{increment:1}}}));
});
sabbathSchoolRouter.delete('/:id',async(req:AuthedRequest,res)=>{
  const id=Number(req.params.id);
  const row=await db.sabbathSchoolEntry.findFirst({where:{id,...scopeWhere(req.user!)}});
  if(!row||!canWriteGroup(req.user!,row.groupId)) return res.status(403).json({message:'Only the owning Itsinda can remove this entry.'});
  await db.sabbathSchoolEntry.delete({where:{id}});
  res.status(204).end();
});
