import {Router} from 'express';
import {db} from '../index.js';
import {auth,AuthedRequest} from '../middleware/auth.js'; import {requireApprovedOfflineDevice} from '../middleware/offlineDevice.js';

export const sabbathSchoolRouter=Router();
sabbathSchoolRouter.use(auth); sabbathSchoolRouter.use(requireApprovedOfflineDevice);

function scopeWhere(u:NonNullable<AuthedRequest['user']>){
  if(u.role==='REGIONAL_LEADER') return {};
  if(u.role==='CHURCH') return {churchId:u.churchId!};
  if(u.role==='SECTION') return {sectionId:u.sectionId!};
  if(u.role==='GROUP') return {groupId:u.groupId!};
  return {id:-1};
}
function canWriteGroup(u:NonNullable<AuthedRequest['user']>,groupId:number){
  return u.role==='GROUP' && u.groupId===groupId;
}

// Entries are created at Itsinda level only. Date is generated by the server.
sabbathSchoolRouter.post('/',async(req:AuthedRequest,res)=>{
  const groupId=Number(req.body.groupId??req.user!.groupId);
  if(!Number.isInteger(groupId)||!canWriteGroup(req.user!,groupId)) return res.status(403).json({message:'Ishuri ryo ku Isabato ryinjizwa n\'Itsinda ryemerewe gusa.'});
  const submissionId=String(req.body.submissionId||'').trim();
  if(submissionId.length<8) return res.status(400).json({message:'submissionId is required'});
  const duplicate=await db.sabbathSchoolEntry.findUnique({where:{submissionId}});
  if(duplicate) return res.json(duplicate);
  const payload=req.body.payload;
  if(!payload||typeof payload!=='object'||Array.isArray(payload)) return res.status(400).json({message:'Statistics payload is required.'});
  const group=await db.group.findUnique({where:{id:groupId},include:{section:true}});
  if(!group||!group.isActive) return res.status(404).json({message:'Itsinda ntiryabonetse.'});
  const row=await db.sabbathSchoolEntry.create({data:{groupId,sectionId:group.sectionId,churchId:group.section.churchId,createdByUserId:req.user!.id,payloadJson:payload,submissionId}});
  res.status(201).json(row);
});

sabbathSchoolRouter.get('/',async(req:AuthedRequest,res)=>{
  const rows=await db.sabbathSchoolEntry.findMany({where:scopeWhere(req.user!),orderBy:{entryDateUtc:'desc'},take:500});
  res.json(rows);
});

// Generic numeric roll-up keeps approved statistics intact without hard-coding new fields.
sabbathSchoolRouter.get('/summary',async(req:AuthedRequest,res)=>{
  const from=req.query.from?new Date(String(req.query.from)):undefined;
  const to=req.query.to?new Date(String(req.query.to)):undefined;
  const where:any={...scopeWhere(req.user!)};
  if(from||to) where.entryDateUtc={...(from?{gte:from}:{}),...(to?{lte:to}:{})};
  const rows=await db.sabbathSchoolEntry.findMany({where,orderBy:{entryDateUtc:'asc'}});
  const totals:Record<string,number>={};
  for(const row of rows){
    const p=row.payloadJson as Record<string,unknown>;
    for(const [k,v] of Object.entries(p)) if(typeof v==='number'&&Number.isFinite(v)) totals[k]=(totals[k]||0)+v;
  }
  res.json({scope:req.user!.role,entryCount:rows.length,totals,from:from?.toISOString()??null,to:to?.toISOString()??null});
});

sabbathSchoolRouter.patch('/:id',async(req:AuthedRequest,res)=>{
  const id=Number(req.params.id);
  const row=await db.sabbathSchoolEntry.findFirst({where:{id,...scopeWhere(req.user!)}});
  if(!row||!canWriteGroup(req.user!,row.groupId)) return res.status(403).json({message:'Only the owning Itsinda can change this entry.'});
  const payload=req.body.payload;
  if(!payload||typeof payload!=='object'||Array.isArray(payload)||!Object.keys(payload).length) return res.status(400).json({message:'Statistics payload is required.'});
  res.json(await db.sabbathSchoolEntry.update({where:{id},data:{payloadJson:payload,revision:{increment:1}}}));
});
sabbathSchoolRouter.delete('/:id',async(req:AuthedRequest,res)=>{
  const id=Number(req.params.id);
  const row=await db.sabbathSchoolEntry.findFirst({where:{id,...scopeWhere(req.user!)}});
  if(!row||!canWriteGroup(req.user!,row.groupId)) return res.status(403).json({message:'Only the owning Itsinda can remove this entry.'});
  await db.sabbathSchoolEntry.delete({where:{id}});
  res.status(204).end();
});
